- src/main/java/longah/node/Member.java
- src/test/java/longah/node/MemberTest.java
Updated Member.java
Added Member JUnit tests
> Junit test 1

- src/main/java/longah/util/TransactionList.java
- src/test/java/longah/node/MemberTest.java
- src/test/java/longah/util/TransactionListTest.java
+ Add misc functions for TransactionList
> Add TransactionList JUnit test

- src/main/java/longah/LongAh.java
- src/main/java/longah/node/Transaction.java
- src/test/java/longah/node/TransactionTest.java
Add Junit tests for Transaction constructor and addPayee
> Add Transaction Junit test

- src/main/java/longah/LongAh.java
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/node/Transaction.java
- src/main/java/longah/util/MemberList.java
- src/main/java/longah/util/Subtransaction.java
- src/main/java/longah/util/TransactionList.java
- src/test/java/longah/node/TransactionTest.java
- src/test/java/longah/util/TransactionListTest.java
- text-ui-test/input.txt
- Refactor code in Transaction.java to use ArrayList instead of Hashmap
- Rename attributes in subtransaction to improve overall code clarity
- Change input format for adding transaction
- Add settlement function to settle/repay debt for a person
> Refactor Transaction and add settlement function

- .gitignore
- src/main/java/longah/LongAh.java
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/handler/StorageHandler.java
- src/main/java/longah/node/Group.java
- src/main/java/longah/node/Member.java
- src/main/java/longah/node/Transaction.java
- src/main/java/longah/util/MemberList.java
- src/main/java/longah/util/TransactionList.java
- src/test/java/longah/node/TransactionTest.java
- src/test/java/longah/util/TransactionListTest.java
Implemented loading from storage
Pending write to storage as of writing this
> Data Storage

- src/main/java/longah/LongAh.java
- src/main/java/longah/node/Group.java
- src/main/java/longah/node/Member.java
- src/main/java/longah/node/Transaction.java
- src/main/java/longah/util/MemberList.java
- src/main/java/longah/util/TransactionList.java
Add recalculation of balances after deleting a transaction and clearing all transactions. Include minor code clean up as well
> Add balance recalculation for delete and clear

- src/main/java/longah/LongAh.java
- src/main/java/longah/commands/ClearCommand.java
- src/main/java/longah/commands/Command.java
- src/main/java/longah/commands/ExitCommand.java
- src/main/java/longah/commands/SettleCommand.java
- src/main/java/longah/commands/add/AddCommand.java
- src/main/java/longah/commands/add/AddMemberCommand.java
- src/main/java/longah/commands/add/AddTransactionCommand.java
- src/main/java/longah/commands/delete/DeleteCommand.java
- src/main/java/longah/commands/delete/DeleteTransactionCommand.java
- src/main/java/longah/commands/find/FindBorrowerCommand.java
- src/main/java/longah/commands/find/FindCommand.java
- src/main/java/longah/commands/find/FindDebtCommand.java
- src/main/java/longah/commands/find/FindLenderCommand.java
- src/main/java/longah/commands/find/FindTransactionCommand.java
- src/main/java/longah/commands/list/ListCommand.java
- src/main/java/longah/commands/list/ListDebtCommand.java
- src/main/java/longah/commands/list/ListMemberCommand.java
- src/main/java/longah/commands/list/ListTransactionCommand.java
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/handler/CommandParser.java
- src/main/java/longah/handler/InputHandler.java
- src/main/java/longah/handler/StorageHandler.java
- src/main/java/longah/node/Group.java
- src/main/java/longah/node/Transaction.java
- src/main/java/longah/util/MemberList.java
- src/main/java/longah/util/Subtransaction.java
- src/main/java/longah/util/TransactionList.java
- src/test/java/longah/util/TransactionListTest.java
- text-ui-test/input.txt
Will include certain refactoring changes in this PR as well
> Output Solution

- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/node/Member.java
- src/main/java/longah/node/Transaction.java
- src/main/java/longah/util/TransactionList.java
- src/test/java/longah/util/TransactionListTest.java
1. Add edit transaction feature
2. Omit edit transaction case in main program to implement in future
3. Add javadoc for recalculateBalances(
4. Add JUnit tests
> Edit transactions

- build.gradle
- src/main/java/longah/LongAh.java
- src/main/java/longah/commands/edit/EditCommand.java
- src/main/java/longah/commands/edit/EditMemberCommand.java
- src/main/java/longah/commands/edit/EditTransactionCommand.java
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/handler/CommandParser.java
- src/main/java/longah/handler/StorageHandler.java
- src/main/java/longah/node/Group.java
- src/main/java/longah/node/Member.java
- src/main/java/longah/node/Transaction.java
- src/main/java/longah/util/MemberList.java
- src/main/java/longah/util/TransactionList.java
- src/test/java/longah/handler/StorageHandlerTest.java
- src/test/java/longah/node/MemberTest.java
- src/test/java/longah/node/TransactionTest.java
- src/test/java/longah/util/MemberListTest.java
- src/test/java/longah/util/TransactionListTest.java
- text-ui-test/runtest.bat
- text-ui-test/runtest.sh
Inclusive of added JUnit tests
> Improve balance calculation and logging class

- src/main/java/longah/commands/ClearCommand.java
- src/main/java/longah/commands/ExitCommand.java
- src/main/java/longah/commands/HelpCommand.java
- src/main/java/longah/commands/SettleCommand.java
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/handler/CommandParser.java
- src/main/java/longah/handler/UI.java
Add a help menu for users to view list of all available commands and some minor fixes.
Currently the full list of commands seems quite long, considering to split help menu into different categories based on command type for easier viewing, to be updated further
> Add help section

- src/main/java/longah/commands/PINCommand.java
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/handler/CommandParser.java
- src/main/java/longah/handler/PINHandler.java
- text-ui-test/EXPECTED.TXT
Refactored PIN commands, improved logic
> Refactor PIN commands and logic

- docs/DeveloperGuide.md
> Developer guide docs jx

- src/main/java/longah/commands/PINCommand.java
- src/main/java/longah/handler/PINHandler.java
- src/test/java/longah/handler/PINHandlerTest.java
- Add methods for JUnit test
- Add JUnit test cases
> Refactor pin feature

- docs/DeveloperGuide.md
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/handler/StorageHandler.java
- src/main/java/longah/node/Transaction.java
- src/test/java/longah/handler/StorageHandlerTest.java
- src/test/java/longah/node/TransactionTest.java
- src/test/java/longah/util/TransactionListTest.java
Time logging increments to Transaction, TransactionList Functions and StorageHandler classes
> Time logging increments

- docs/diagrams/LongAh.puml
- src/main/java/longah/LongAh.java
> Add UML diagram

- src/main/java/longah/LongAh.java
- src/main/java/longah/handler/UI.java
- text-ui-test/EXPECTED1.TXT
1. Integrate welcome message
2. Fix welcome UI issue
> Fix welcome message

- src/main/java/longah/commands/filter/FilterCommand.java
- src/main/java/longah/commands/filter/FilterDateTimeCommand.java
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/handler/InputHandler.java
- src/main/java/longah/node/DateTime.java
- src/main/java/longah/node/Transaction.java
- src/main/java/longah/util/TransactionList.java
- src/test/java/longah/node/TransactionTest.java
Increments pertaining to time filter.
> Time filter

- src/main/java/longah/commands/filter/FilterDateTimeCommand.java
- src/main/java/longah/exception/ExceptionMessage.java
- src/main/java/longah/node/DateTime.java
- src/main/java/longah/node/Transaction.java
- src/main/java/longah/util/TransactionList.java
- src/test/java/longah/node/TransactionTest.java
- src/test/java/longah/util/TransactionListTest.java
Functional tweaks for DateTime and TransactionList methods to resolve bugs reflected in PED.
> PED fixes for DateTime and TransactionList methods

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/longah/handler/PINHandler.java
- text-ui-test/EXPECTED1.TXT
> Fix PIN authentication consistency

- src/main/java/longah/commands/ClearCommand.java
Fix PED feature flaw for 'clear' command
> Add ClearCommand warning message

- src/main/java/longah/commands/ClearCommand.java
> Remove WARNING keyword

- docs/DeveloperGuide.md
- docs/UserGuide.md
edit documentation to reflect new chart command
> Update new ChartCommand documentation

- src/main/java/longah/commands/list/ListDebtCommand.java
- src/main/java/longah/commands/list/ListGroupsCommand.java
- src/main/java/longah/commands/list/ListMemberCommand.java
- src/main/java/longah/commands/list/ListTransactionCommand.java
- src/main/java/longah/handler/StorageHandler.java
- src/test/java/longah/handler/PINHandlerTest.java
Error in double representation causing storage checksum to fail.
> P0: Fix double representation bug in storage

- docs/team/jing-xiang.md
> Update PPP jingxiang.md

- docs/DeveloperGuide.md
@djleong01 @FeathersRe  to ensure that your PRs follow standard of class names being called in a code segment.
> DG Formatting

- docs/team/feathersre.md
Final updates for individual PPP.
> PPP updates

- docs/team/feathersre.md
> PPP spacing updates
